# Artificial Neural Networks (ANNs)

## Data Pre-Processing

### Importing the Libraries

In [65]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [66]:
tf.__version__

'2.12.0'

### Import the Dataset

In [67]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [68]:
  X = dataset.iloc[:, 3:-1].values
  y = dataset.iloc[:, -1].values

In [69]:
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


### Encoding Categorical Data
Female -> 0 Male -> 1

In [70]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

X[:, 2] = le.fit_transform(X[:, 2])

In [71]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [72]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [73]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the Dataset

In [74]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling (Absolutely Compulsory for Deep Learning)

In [75]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Building the ANN

### Initializing the ANN

In [76]:
ann = tf.keras.models.Sequential()

### Adding the Input Layer and the first Hidden Layer
**Note**: Codename for rectifier activision function is 'relu'

In [77]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second Hidden Layer

In [78]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the Output Layer
**Note**: Use sigmoid activation function for output layer only because it also gives probability.

In [79]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## Training the ANN

### Compiling the ANN
**Note**: For binary classification, loss = binary_crossentropy
and for categorical classification, loss = categorical_crossentropy

In [80]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN
**Note**: We are doing Batch Learning

In [81]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6199 - accuracy: 0.7171
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4893 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4550 - accuracy: 0.7976
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4352 - accuracy: 0.8092
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4230 - accuracy: 0.8126
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4154 - accuracy: 0.8169
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4098 - accuracy: 0.8216
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4053 - accuracy: 0.8239
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4005 - accuracy: 0.8249
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3936 - accura

## Making the Prediction and Evaluating the Model
**Note**: Answer will come in terms of probability because of sigmoid function.

In [90]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 94ms/step
[[False]]


In [84]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(y_pred)

63/63 [==============================] - 0s 756us/step
[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [85]:
y_pred = le.fit_transform(y_pred)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [86]:
print(y_pred)

[0 0 0 ... 0 0 0]


In [88]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[1495  100]
 [ 184  221]]
0.858


# DONE!