# Spam Mail Detection
We will detect whether a mail is spam or ham with the help of Logistic Regression model.

## Import the libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

## Data Pre-Processing

### Importing the dataset

In [4]:
dataset = pd.read_csv('mail_data.csv')
print(dataset)

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]


In [5]:
dataset = dataset.where((pd.notnull(dataset)), '')

In [6]:
dataset.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
dataset.shape

(5572, 2)

In [8]:
dataset['Category'].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

### Seperating dependent and independent variables

In [9]:
y = dataset.iloc[:, 0].values
X = dataset.iloc[:, -1].values

print(X)
print(y)

['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
 'Ok lar... Joking wif u oni...'
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
 ... 'Pity, * was in mood for that. So...any other suggestions?'
 "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"
 'Rofl. Its true to its name']
['ham' 'ham' 'spam' ... 'ham' 'ham' 'ham']


### Label Encoding the dependent variable

Spam --> 1
Ham --> 0

In [10]:
encoder = LabelEncoder()
y = encoder.fit_transform(y)

print(y)

[0 0 1 ... 0 0 0]


### Splitting the dataset into training and testing set

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [12]:
print(X.shape, X_train.shape, X_test.shape)

(5572,) (4457,) (1115,)


### Feature Extraction

In [13]:
extraction = TfidfVectorizer(min_df = 1, stop_words = 'english', lowercase = True)

X_train_features = extraction.fit_transform(X_train)
X_test_features = extraction.transform(X_test)

In [14]:
print(X_train_features)

  (0, 3422)	0.6418008618863358
  (0, 3960)	0.40459749284424307
  (0, 4776)	0.2937599690543961
  (0, 4486)	0.4933198981059812
  (0, 3101)	0.30778739607068667
  (1, 3855)	0.4410710256765374
  (1, 4574)	0.4410710256765374
  (1, 2534)	0.4410710256765374
  (1, 814)	0.4410710256765374
  (1, 4555)	0.4205367990464199
  (1, 2902)	0.2120712188920981
  (2, 3398)	0.5133141633463273
  (2, 1317)	0.34462014146959175
  (2, 432)	0.4077104256374456
  (2, 4294)	0.36445133334144264
  (2, 2503)	0.5133141633463273
  (2, 4776)	0.2349500626979615
  (3, 1138)	0.6489221209014988
  (3, 1160)	0.44843330753299465
  (3, 3378)	0.38536596088088965
  (3, 3118)	0.3618113574629584
  (3, 3778)	0.31367701143832527
  (4, 3805)	1.0
  (5, 3731)	0.6020708068994186
  (5, 7381)	0.7984426989330436
  :	:
  (4454, 348)	0.2816333253882664
  (4454, 110)	0.3000941484572203
  (4454, 2067)	0.25658354936739225
  (4454, 4488)	0.3000941484572203
  (4454, 651)	0.3000941484572203
  (4454, 373)	0.23959800001827322
  (4454, 796)	0.28163332538

In [15]:
print(X_test_features)

  (0, 7478)	0.11238527640544621
  (0, 7420)	0.19398477272351503
  (0, 7260)	0.14384114349719565
  (0, 6602)	0.19398477272351503
  (0, 6350)	0.19398477272351503
  (0, 5782)	0.11386086683184304
  (0, 5452)	0.13293730388210073
  (0, 5038)	0.19398477272351503
  (0, 5014)	0.13293730388210073
  (0, 4496)	0.1102105484474495
  (0, 4466)	0.16951508500886583
  (0, 4302)	0.17357598220109133
  (0, 4250)	0.19398477272351503
  (0, 4004)	0.17357598220109133
  (0, 3867)	0.3120289176577842
  (0, 3630)	0.19398477272351503
  (0, 3310)	0.3946343133427287
  (0, 3136)	0.19398477272351503
  (0, 3060)	0.38796954544703005
  (0, 3059)	0.2772755538586351
  (0, 2114)	0.1302342007925869
  (0, 1493)	0.1368549641200954
  (0, 524)	0.19398477272351503
  (1, 7163)	0.4130504232751816
  (1, 7014)	0.39097385770203663
  :	:
  (1109, 2086)	0.3511723226114505
  (1110, 6677)	0.278010885413778
  (1110, 6020)	0.35653930858248284
  (1110, 5001)	0.39666689104890435
  (1110, 3863)	0.2030867005199339
  (1110, 3207)	0.36236761338841

## Training the Model

### Fitting the Logistic Regression model

In [16]:
classifier = LogisticRegression()

classifier.fit(X_train_features, y_train)

LogisticRegression()

### Predicting the outcome from our trained model

In [17]:
y_pred = classifier.predict(X_test_features)
print(y_pred)

[0 0 0 ... 0 0 0]


## Evaluating the Model

### Confusion Matrix

In [18]:
print(confusion_matrix(y_test, y_pred))

[[954   1]
 [ 36 124]]


### Classification Report

In [19]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       955
           1       0.99      0.78      0.87       160

    accuracy                           0.97      1115
   macro avg       0.98      0.89      0.93      1115
weighted avg       0.97      0.97      0.97      1115



### Accuracy Score

In [20]:
print(accuracy_score(y_test, y_pred))

0.9668161434977578


## Building a Predictive System

In [21]:
input_mail = ["As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune"]

#convert text to feature vectors
input_mail = extraction.transform(input_mail)

#making predictions
prediction = classifier.predict(input_mail)

if(prediction == 1):
  print("It's a spam mail.")
else:
  print("It's a ham mail.")

It's a ham mail.


# DONE!